//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_smsEntities : DbContext
    {
        public db_smsEntities()
            : base("name=db_smsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_batch> tb_batch { get; set; }
        public virtual DbSet<tb_course> tb_course { get; set; }
        public virtual DbSet<tb_registration> tb_registration { get; set; }
        public virtual DbSet<tb_user> tb_user { get; set; }
    }
}
